server:
  port: 8080

spring:
  security:
    filter:
      dispatcher:
        ignore: "/swagger-ui/**,/v3/api-docs/**"
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-1.0.yaml


security:
  jwt:
    token:
      secret-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      expire-length: 3600000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    ru.company.ru.company.taskmanagementsystem: DEBUG